### ISSUE TITLE
Deprecated class UIWebView

### ISSUE THREAD

**Issue by OJDee** [Judopay/JudoKitObjC#118]
Apple has begun to send warnings on every submission to AppStoreConnect warning of use of a deprecated class, UIWebView

3DSWebView inherits UIWebView
JudoPayViewController conforms to UIWebViewDelegate

The use of WKWebView is assumed as a direct replacement for WKWebView. Is this update planned for JudoKit?

**Comment by freddy-onco** [comment]
@OJDee  thank you , we are aware of this necessary change , and we will carry out an upgrade of the SDK

**Comment by freddy-onco** [comment]
@OJDee  https://github.com/Judopay/JudoKitObjC/pull/119

**Comment by zfoltin** [comment]
This update was part of the [8.0](https://github.com/Judopay/JudoKitObjC/releases/tag/8.0.0) release 🚀
