### ISSUE TITLE
JPAmount Convenient initializer for amount error

### ISSUE THREAD

**Issue by yberdnikov** [Judopay/JudoKitObjC#40]
In file 'JPAmount.m' implementation of method `+ (nonnull instancetype)amount:(nonnull NSString *)amount currency:(nonnull NSString *)currency;` has typo:

```
+ (instancetype)amount:(NSString *)amount currency:(NSString *)currency {
    return [[JPAmount alloc] initWithAmount:amount currency:amount];
}
```

Currency parameter is ignored and not passed to initializer.

Issue is in the latest sources https://github.com/JudoPay/JudoKitObjC/blob/master/Source/Model/JPAmount.m#L37

**Comment by AlbMata** [comment]
Hi Yuriy,

Thanks for contacting us. Allow us to take a look on that with our iOS developers. We will come back to you very shortly.

Best regards,

**Comment by AlbMata** [comment]
Hi,

Apologies for the double post. We have seen that this issue was requested on 29th august so apologies for that huge delay. We will plan a fix to that issue for the next release.

We will keep you posted as soon as we update.

Regards,
