### ISSUE TITLE
how to validate Card number using Judokit in customization

### ISSUE THREAD

**Issue by smilydronavalli** [Judopay/JudoKitObjC#80]
Hi,

I need to validate card number in my own customisation screen.Please can you help how to do that one.I am using Objective C.

ThanksInAdvance

**Comment by mikehancock** [comment]
Hi,
Unfortunately we can't advise you on card validation if you chose to build your own UI. The SDK is designed to minimise the scope of your PCI compliance and as such if you chose to build your own UI we cannot advise.
